version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sap123ok
      MYSQL_DATABASE: test
      MYSQL_USER: hakim
      MYSQL_PASSWORD: sap123ok
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
